import type { ResearchDetail } from '../types/content'
import { apparatus, text } from './researchDetailHelpers'

export const systemResearchDetails: Record<string, ResearchDetail> = {
  'vacuum-laser': {
    principle: text('真空由气载、流导和有效抽速决定，激光由参考、频率转换、调制和末端交付组成。所有基础设施指标最终必须在科学腔与原子面闭环，不能停在泵或激光器出口。', 'Vacuum follows gas load, conductance and effective pumping speed, while each laser chain comprises a reference, conversion, modulation and endpoint delivery. Infrastructure acceptance closes at the science cell and atom plane, not at pump or laser output.'),
    equations: [
      { expression: String.raw`P=Q/S_{\rm eff},\qquad \tau_{\rm trap}^{-1}=\sum_i n_i\langle\sigma_i v_i\rangle`, explanation: text('总压力、RGA 组分和原子寿命需同步解释，不能从单个规管读数推出局部寿命。', 'Total pressure, RGA composition and atom lifetime require joint interpretation; one gauge cannot predict local lifetime.') },
      { expression: String.raw`\delta\phi_{\rm atom}=\delta\phi_{\rm source}+\delta\phi_{\rm path}+\delta\phi_{\rm actuator}`, explanation: text('原子端相位包含源、传输路径和调制执行器三部分。', 'Atom-plane phase includes source, delivery path and modulation actuator contributions.') },
    ],
    instruments: [
      apparatus('离子泵、NEG、真空计与 RGA', 'Ion pump, NEG, gauges and RGA', '维持 UHV 并区分总压和组分。', 'Maintain UHV and separate total pressure from composition.', '压力、泵电流、RGA 谱、恢复时间和原子寿命。', 'Pressure, pump current, RGA spectrum, recovery and atom lifetime.'),
      apparatus('Yb 原子炉、快门与差分抽气', 'Yb oven, shutter and differential pumping', '提供通量并隔离科学腔污染。', 'Provide flux while isolating science-cell contamination.', '炉温—装载—压力—污染联合曲线。', 'Oven-temperature/loading/pressure/contamination curve.'),
      apparatus('399/556/578/302 nm 激光链', '399/556/578/302 nm laser chains', '完成冷却、钟态映射和 Rydberg 激发。', 'Perform cooling, clock mapping and Rydberg excitation.', '线宽、拍频、锁误差、末端功率/相位/光斑/偏振。', 'Linewidth, beat note, lock error and delivered power/phase/spot/polarization.'),
    ],
    procedure: [text('完成材料清单、清洁、氦检和分区烘烤，保存温度/压力/RGA 全时序。', 'Complete materials, cleaning, helium leak test and zoned bake with full temperature/pressure/RGA timelines.'), text('降温后建立背景谱，分级打开原子炉并测科学腔压力和恢复。', 'Establish background spectra after cooldown, then step the oven and measure science-cell pressure/recovery.'), text('逐条激光链验收源端频率、转换、调制、传输和安全联锁。', 'Accept each laser chain through source frequency, conversion, modulation, delivery and interlocks.'), text('用 MOT、光谱、Rabi/Ramsey 和寿命在原子端复核。', 'Verify at atoms with MOT, spectra, Rabi/Ramsey and lifetime.'), text('真空开腔、UV 维护、光纤更换或软件升级后执行分层回归。', 'Run layered regression after vacuum access, UV service, fiber replacement or software upgrade.')],
    outputs: [text('真空拓扑、材料/烘烤/泄漏记录和基线 RGA。', 'Vacuum topology, material/bake/leak records and baseline RGA.'), text('各波长源端到原子面的功率、频率、相位与传递函数。', 'Power, frequency, phase and transfer functions from source to atoms for each wavelength.'), text('炉温—通量—污染关系和维护阈值。', 'Oven temperature-flux-contamination relation and service thresholds.')],
    milestone: text('真空和四条激光链可独立验收，并能由原子响应复核', 'Vacuum and all four laser chains are independently accepted and atom-verified'),
    acceptance: [text('压力/RGA 在规定恢复时间内稳定，原子寿命与组分一致。', 'Pressure/RGA stabilize within the recovery window and atom lifetime agrees with composition.'), text('每条光链有源端/末端监测、锁定余量、失锁处理和联锁记录。', 'Each optical chain has source/end monitoring, lock margin, unlock handling and interlock records.'), text('维护后可由版本化回归恢复，不依赖个人记忆。', 'Service recovery follows versioned regression rather than personal memory.')],
    theoryToExperiment: text('理论提供气载—寿命、转换效率和相噪传播模型；实验返回时序对齐的真空、光学和原子数据。', 'Theory provides gas-load/lifetime, conversion-efficiency and phase-noise propagation models; experiment returns time-aligned vacuum, optical and atomic data.'),
  },
  'control-calibration': {
    principle: text('控制系统必须区分数字指令与物理响应。FPGA 给出确定性事件，AWG/DDS 给出波形，AOM/EOM、线圈和相机形成各自传递函数；校准沿因果链从参考时钟推进到原子。', 'Control distinguishes digital commands from physical responses. FPGA supplies deterministic events, AWG/DDS waveforms, and AOM/EOM, coils and cameras add transfer functions; calibration proceeds causally from the master clock to atoms.'),
    equations: [{ expression: String.raw`y_i(t)=h_i(t)*u_i(t-\tau_i)+\epsilon_i(t),\qquad t_{\rm atom}=t_{\rm FPGA}+\tau_{\rm IO}+\tau_{\rm chain}`, explanation: text('标定对象是每条链的传递函数、延迟及漂移，而不只是设定值。', 'Calibration targets each chain transfer function, delay and drift rather than setpoints alone.') }],
    instruments: [
      apparatus('主参考、频率计与示波器', 'Master reference, counter and oscilloscope', '统一频率基准并测数字/模拟时序。', 'Unify frequency reference and measure digital/analog timing.', '锁定、相噪、延迟、RMS/峰值抖动。', 'Lock, phase noise, latency and RMS/peak jitter.'),
      apparatus('FPGA、AWG、DDS 与 RF 分析', 'FPGA, AWG, DDS and RF analysis', '生成并验证触发、频率、相位和包络。', 'Generate and verify triggers, frequency, phase and envelope.', '波形、互调、正反向功率、压缩和过冲。', 'Waveform, intermodulation, forward/reflected power, compression and overshoot.'),
      apparatus('PD、曝光输出与原子探针', 'Photodiodes, exposure output and atomic probes', '测实际光脉冲、曝光和最终响应。', 'Measure real optical pulses, exposure and final response.', '末端功率/相位、曝光窗口、Rabi、光移和磁场。', 'Delivered power/phase, exposure window, Rabi, light shift and field.'),
    ],
    procedure: [text('锁定所有设备到一个主参考，记录时钟域、PLL 与失锁策略。', 'Lock all devices to one master and record clock domains, PLL and unlock policy.'), text('逐通道测 TTL→RF→光/线圈/曝光的端到端延迟和传递函数。', 'Measure end-to-end TTL-to-RF-to-light/coil/exposure delays and transfer functions.'), text('按功率/频率→阱深/温度→磁场→Rabi→AC Stark→串扰→双原子相互作用顺序标定。', 'Calibrate in order: power/frequency, trap depth/temperature, field, Rabi, AC Stark, crosstalk and two-atom interaction.'), text('注入失锁、相机超时、放大器压缩和通信中断，验证安全状态。', 'Inject unlock, camera timeout, amplifier compression and communication loss to verify safe states.'), text('每个 shot 冻结配置、波形、标定和设备状态哈希。', 'Freeze configuration, waveform, calibration and device-state hashes per shot.')],
    outputs: [text('数字事件到原子响应的延迟/传递函数表。', 'Delay/transfer table from digital events to atomic responses.'), text('校准依赖图、版本有效期和自动重标阈值。', 'Calibration dependency graph, validity windows and automatic thresholds.'), text('每-shot 配置哈希、帧号、时间戳、锁定位和异常位。', 'Per-shot configuration hash, frame ID, timestamp, lock and exception flags.')],
    milestone: text('任何原子结果都可追溯到实际波形、物理响应和标定版本', 'Every atomic result is traceable to actual waveform, physical response and calibration version'),
    acceptance: [text('最坏端到端延迟和抖动满足预算，不以平均值替代。', 'Worst-case end-to-end latency and jitter meet budget; averages are insufficient.'), text('上游标定失败时阻止下游门数据放行。', 'Upstream calibration failure blocks downstream gate data release.'), text('重启、升级和换设备后自动执行接口回归并生成差异。', 'Restart, upgrade and replacement trigger interface regression and a difference report.')],
    theoryToExperiment: text('理论使用实测传递函数、噪声谱和延迟输出硬件可执行波形；实验返回设定与实际响应的同步记录。', 'Theory uses measured transfer functions, spectra and delays to produce executable waveforms; experiment returns synchronized command/response records.'),
  },
  'inverse-problem': {
    principle: text('理论首先判断哪些参数能由现有观测辨识，以及下一项测量能否区分候选假设。谱线、Rabi/Ramsey、温度、寿命和关联数据必须通过同一生成模型映射到哈密顿量与噪声参数。', 'Theory first asks which parameters are identifiable and whether the next measurement distinguishes candidate hypotheses. Spectra, Rabi/Ramsey, temperature, lifetime and correlations require one generative model mapping to Hamiltonian and noise parameters.'),
    equations: [{ expression: String.raw`p(\theta|D,M)\propto p(D|\theta,M)p(\theta|M),\qquad \Sigma_y=J\Sigma_\theta J^\mathsf T+\Sigma_{\rm model}`, explanation: text('预测不确定度由参数后验和模型缺失共同构成；最佳拟合值会隐藏不可辨识方向。', 'Predictive uncertainty combines parameter posterior and model discrepancy; a best fit hides unidentifiable directions.') }],
    instruments: [
      apparatus('谱线、Rabi/Ramsey 与寿命数据', 'Spectra, Rabi/Ramsey and lifetime data', '互补约束频率、耦合、相干与损失。', 'Complementarily constrain frequency, coupling, coherence and loss.', '原始 shot、扫描轴、环境量、SPAM 和条件化规则。', 'Raw shots, scan axes, environment, SPAM and conditioning rules.'),
      apparatus('温度、光斑、磁场与噪声诊断', 'Temperature, beam, field and noise diagnostics', '独立锁定输入，减少拟合退化。', 'Independently lock inputs and reduce fit degeneracy.', 'TOF/边带、PSF、Stokes、场图和功率/相位 PSD。', 'TOF/sidebands, PSF, Stokes, field maps and power/phase PSD.'),
      apparatus('版本化模型与拟合流水线', 'Versioned model and fit pipeline', '重现近似、单位、先验和数据选择。', 'Reproduce approximations, units, priors and data selection.', '参数表、代码哈希、残差、后验和预测。', 'Parameter table, code hash, residuals, posterior and predictions.'),
    ],
    procedure: [text('列出基底、近似、固定/拟合参数和缺失项，先做量纲与极限检查。', 'List basis, approximations, fixed/fitted parameters and omissions; check dimensions and limits first.'), text('用独立实验锁定可测参数，避免所有参数同时吸收误差。', 'Lock measurable parameters independently rather than let all absorb errors.'), text('联合拟合多组数据，保留参数相关、后验预测和结构化残差。', 'Jointly fit datasets and retain correlations, posterior predictions and structured residuals.'), text('用留出功率、站点、温度或时间检验预测，失败时比较模型结构。', 'Test on held-out power, site, temperature or time; compare model structures on failure.'), text('按预期信息增益选择下一测量，声明所需精度与停止条件。', 'Choose the next measurement by expected information gain with required precision and stopping condition.')],
    outputs: [text('带来源、单位、证据等级和协方差的参数注册表。', 'Parameter registry with source, units, evidence grade and covariance.'), text('可执行模型、拟合脚本、原始数据索引和预测检查。', 'Executable model, fit scripts, raw-data index and predictive checks.'), text('误差预算、灵敏度、缺失数据和下一项判别性测量。', 'Error budget, sensitivities, missing data and next discriminating measurement.')],
    milestone: text('模型预测留出数据并指导下一项最有信息量的实验', 'The model predicts held-out data and directs the next most informative experiment'),
    acceptance: [text('参数、单位、基底和损失/SPAM 条件化与实验一致。', 'Parameters, units, basis and loss/SPAM conditioning match experiment.'), text('后验预测覆盖留出数据，残差无未解释结构。', 'Posterior predictions cover held-out data without unexplained residual structure.'), text('误差项不重复计数；缺失参数只产生范围，不产生架构结论。', 'Errors are not double counted; missing parameters produce ranges, not architecture claims.')],
    theoryToExperiment: text('每轮交付可执行扫描、允许漂移、失败判据和更新证据；实验返回未筛选数据及完整条件化。', 'Each iteration delivers executable scans, drift tolerance, failure criteria and evidence; experiment returns unscreened data and complete conditioning.'),
  },
  'erasure-conversion': {
    principle: text('擦除只有在错误位置被可靠标记、未标记残余通道足够小且检测/复位开销进入完整周期时才有优势。Yb 亚稳态或泄漏可提供标签，但召回、误报、散射和补原子必须联合表征。', 'Erasure helps only when fault locations are reliably flagged, residual unflagged error is small and detection/reset overhead enters the full cycle. Yb metastable/leakage states can provide flags, but recall, false positives, scattering and replacement require joint characterization.'),
    equations: [{ expression: String.raw`\mathcal N=(1-p_f)\mathcal N_0\otimes|0\rangle\langle0|_f+p_f\mathcal N_f\otimes|1\rangle\langle1|_f`, explanation: text('解码器需要未标记通道 N0、已标记通道 Nf、相关性和标签混淆，而不只是 pf。', 'A decoder needs unflagged N0, flagged Nf, correlations and flag confusion, not pf alone.') }],
    instruments: [
      apparatus('状态选择 shelving/repump 与成像', 'State-selective shelving/repump and imaging', '区分亚稳态、泄漏、计算态和真空。', 'Distinguish metastable, leakage, computational and vacuum outcomes.', '召回、误报、损失、散射和邻站点串扰。', 'Recall, false positives, loss, scattering and neighbor crosstalk.'),
      apparatus('快速相机、FPGA 与实时分类', 'Fast camera, FPGA and real-time classification', '在逻辑周期内产生位置/时间标签。', 'Produce location/time flags within the logical cycle.', '曝光—传输—判别—输出延迟及长尾。', 'Exposure-transfer-classification-output latency and tails.'),
      apparatus('补原子、调度与解码器', 'Replacement, scheduler and decoder', '恢复阵列并评估逻辑净收益。', 'Restore the array and evaluate net logical benefit.', '补原子时间、温升、冲突、解码输入和逻辑结果。', 'Replacement time, heating, conflicts, decoder input and logical result.'),
    ],
    procedure: [text('定义每种物理事件及标签，保持“存在但泄漏”和“原子损失”分离。', 'Define each event and flag, keeping present-but-leaked separate from atom loss.'), text('用已知事件标定 P(flag|event)，按站点、时间和并行密度报告。', 'Calibrate P(flag|event) with known events by site, time and parallel density.'), text('分别表征标记和未标记 shot，不把标记结果简单删除。', 'Characterize flagged and unflagged shots separately rather than deleting flags.'), text('把检测、反馈、复位、补原子和调度插入真实逻辑周期。', 'Insert detection, feedback, reset, replacement and scheduling into the real cycle.'), text('用同一解码器比较无擦除、理想擦除和实测标签，并消融开销。', 'Compare no-erasure, ideal-erasure and measured flags with one decoder and ablate overheads.')],
    outputs: [text('事件—结果—标签字典和站点混淆矩阵。', 'Event-outcome-flag dictionary and site confusion matrices.'), text('N0、Nf、泄漏/损失/Pauli 分量及相关性。', 'N0, Nf, leakage/loss/Pauli components and correlations.'), text('完整周期、补原子代价、逻辑错误率和净收益工作区。', 'Full cycle, replacement cost, logical error and net-benefit regime.')],
    milestone: text('证明实测标签在完整周期中降低逻辑错误，而非只提高可检测比例', 'Show that measured flags lower logical error in the full cycle rather than only increasing detectability'),
    acceptance: [text('召回、误报、检测时间和残余未标记错误全部带区间。', 'Recall, false positives, detection time and residual unflagged error carry intervals.'), text('条件化规则在采数前锁定，原始与条件结果同时报告。', 'Conditioning is locked before acquisition and raw/conditioned results are both reported.'), text('包含散射、退相干、补原子和调度后净逻辑收益仍成立。', 'Net logical benefit remains after scattering, dephasing, replacement and scheduling.')],
    theoryToExperiment: text('理论把实测条件通道和时序开销接入解码器，返回最敏感标签指标；实验围绕它设计下一项测量。', 'Theory feeds measured conditional channels and timing overhead into the decoder and returns the most sensitive flag metric; experiment designs the next measurement around it.'),
  },
}
