import type { ResearchDetail } from '../types/content'
import { apparatus, text } from './researchDetailHelpers'

export const foundationResearchDetails: Record<string, ResearchDetail> = {
  'state-measurement': {
    principle: text('量子态是对一组测量结果给出概率的算符，不是单次 shot 可读取的隐藏变量。实验必须共同定义制备映射、分析基和测量 POVM，再从重复计数估计状态；“态保真度”必须传播 SPAM 与基旋转误差。', 'A quantum state assigns probabilities to measurement outcomes rather than exposing a hidden value in one shot. Preparation, analysis bases and the measurement POVM must be defined jointly before repeated counts estimate a state; state fidelity must propagate SPAM and basis-rotation errors.'),
    equations: [
      { expression: String.raw`p(m|\rho)=\mathrm{Tr}(E_m\rho),\quad E_m\ge0,\quad\sum_mE_m=I`, explanation: text('Born 规则把密度矩阵和实际测量算符映射为结果概率。', 'The Born rule maps a density matrix and real measurement operators to outcome probabilities.') },
      { expression: String.raw`\hat\rho=\arg\max_{\rho\ge0,\,\mathrm{Tr}\rho=1}p(D|\rho,M_{\rm SPAM})`, explanation: text('重构须保持正定和归一，并把测量模型作为联合参数或不确定量。', 'Reconstruction preserves positivity and trace while treating the measurement model as a joint parameter or uncertainty.') },
    ],
    instruments: [
      apparatus('AWG/相干控制源', 'AWG/coherent source', '实现 X/Y/Z 分析基并保存相位参考。', 'Implement X/Y/Z analysis bases with phase traceability.', '脉冲幅度、相位、延迟和 Rabi/Ramsey 基线。', 'Pulse amplitude, phase, delay and Rabi/Ramsey baselines.'),
      apparatus('状态选择读出与科学相机', 'State-selective readout and scientific camera', '将量子态映射为亮、暗、泄漏或损失。', 'Map states to bright, dark, leakage or loss.', '原始帧、PSF 光子数、FP/FN、损失和泄漏。', 'Raw frames, PSF photons, FP/FN, loss and leakage.'),
      apparatus('FPGA 与公共时钟', 'FPGA and common clock', '把制备、旋转、曝光和结果绑定到同一 shot。', 'Bind preparation, rotation, exposure and outcome to one shot.', '物理曝光窗口、触发延迟、波形哈希和异常位。', 'Physical exposure window, trigger delay, waveform hash and exception flags.'),
    ],
    procedure: [text('分别制备 |0⟩、|1⟩、空站点和可识别泄漏参考，建立测量混淆矩阵。', 'Prepare |0>, |1>, empty and identifiable leakage references to build the measurement confusion matrix.'), text('用 Rabi/Ramsey 标定分析脉冲，并绑定功率、频率、相位和时间戳。', 'Calibrate analysis pulses with Rabi/Ramsey and bind power, frequency, phase and timestamps.'), text('随机化测量基与扫描顺序，保存逐 shot 原始结果而非只保存平均布居。', 'Randomize basis and scan order; retain shot-resolved outcomes rather than averages only.'), text('使用约束似然联合估计状态与 SPAM，并用留出测量基验证预测。', 'Jointly estimate state and SPAM with constrained likelihood and verify on held-out bases.')],
    outputs: [text('测量 POVM、混淆矩阵及有效期。', 'Measurement POVM, confusion matrix and validity window.'), text('密度矩阵及统计/系统不确定度。', 'Density matrix with statistical/systematic uncertainty.'), text('原始、条件化和校正指标并列表。', 'Side-by-side raw, conditioned and corrected metrics.')],
    milestone: text('获得能预测留出测量结果的制备—控制—读出联合模型', 'A preparation-control-readout model that predicts held-out measurements'),
    acceptance: [text('参考态交叉验证残差与 shot 噪声一致。', 'Reference-state cross-validation residuals agree with shot noise.'), text('重构态正定且迹为 1，区间包含 SPAM 和基旋转误差。', 'The reconstructed state is positive and trace one, with SPAM and rotation errors included.'), text('漂移超预算时触发重标定，不沿用旧混淆矩阵。', 'Drift beyond budget triggers recalibration rather than reuse of an old matrix.')],
    theoryToExperiment: text('理论交付似然函数、可辨识性与最少测量基；实验返回未筛选计数、校准后验和留出数据。', 'Theory delivers likelihood, identifiability and a minimal basis set; experiment returns unscreened counts, calibration posterior and held-out data.'),
  },
  'cool-trap-image': {
    principle: text('399 nm 宽线提供捕获速度，556 nm 窄线降低温度；远失谐光镊由动态极化率形成势，高 NA 物镜完成聚焦与荧光收集。冷却、装载、成像和重排必须作为同一相空间闭环验收。', 'The broad 399 nm line provides capture velocity, the narrow 556 nm line lowers temperature, and far-detuned tweezers form potentials through dynamic polarizability. High-NA optics focus traps and collect fluorescence, so cooling, loading, imaging and rearrangement are one phase-space loop.'),
    equations: [
      { expression: String.raw`F_{\rm sc}\simeq\hbar k\frac{\Gamma}{2}\frac{s}{1+s+4(\Delta-kv)^2/\Gamma^2}`, explanation: text('散射力说明线宽、饱和度、失谐和速度如何共同决定冷却。', 'Scattering force links linewidth, saturation, detuning and velocity to cooling.') },
      { expression: String.raw`U(\mathbf r)=-\frac{\mathrm{Re}[\alpha(\omega)]I(\mathbf r)}{2\epsilon_0c},\quad\omega_r\simeq\sqrt{4|U_0|/(mw_0^2)}`, explanation: text('偶极势和径向阱频连接极化率、原子面强度、腰斑和质量。', 'Dipole potential and radial frequency connect polarizability, atom-plane intensity, waist and mass.') },
    ],
    instruments: [
      apparatus('399/556 nm 激光、锁频与 AOM', '399/556 nm lasers, locks and AOMs', '产生两级 MOT 的失谐、功率和斜坡。', 'Generate detuning, power and ramps for both MOT stages.', '拍频、锁误差、末端功率、偏振和脉冲波形。', 'Beat note, lock error, delivered power, polarization and pulse shape.'),
      apparatus('MOT/补偿线圈与低噪声电流源', 'MOT/compensation coils and low-noise current sources', '建立零点、梯度和量子化轴。', 'Set field zero, gradient and quantization axis.', '电流—磁场矩阵、关断瞬态、均匀性与热漂。', 'Current-field matrix, turn-off transient, uniformity and thermal drift.'),
      apparatus('SLM/AOD、高 NA 物镜与相机', 'SLM/AOD, high-NA objective and camera', '生成阵列、聚焦、成像和重排。', 'Generate arrays, focus, image and rearrange.', '站点坐标、PSF、阱频、光强均匀和占据混淆矩阵。', 'Site coordinates, PSF, trap frequency, intensity uniformity and occupancy confusion matrix.'),
    ],
    procedure: [text('补偿三轴残磁场；逐束记录原子面功率、光斑、重合和偏振。', 'Compensate three-axis residual fields and record atom-plane power, profile, overlap and polarization for each beam.'), text('二维扫描 399 nm 失谐与梯度，拟合装载曲线以分离捕获率和背景损失。', 'Scan 399 nm detuning versus gradient and fit loading curves to separate capture and background loss.'), text('执行 556 nm 宽频捕获—窄频压缩，并用 TOF/释放再捕获测温。', 'Run broadband capture to narrow compression at 556 nm and measure temperature by TOF/release-recapture.'), text('扫描光镊转移时刻和阱深，逐站点建立 PSF、装载概率和阱频。', 'Scan tweezer transfer time and depth; map site PSF, loading probability and trap frequency.'), text('执行占据识别—路径规划—AOD 搬运—复核成像，分别记录各类失败。', 'Run occupancy inference, path planning, AOD transport and verification imaging with separated failure classes.')],
    outputs: [text('MOT 装载率、温度、云尺寸和两级转移效率。', 'MOT loading, temperature, cloud size and two-stage transfer efficiency.'), text('逐站点阱频、PSF、装载概率和成像混淆矩阵。', 'Site trap frequencies, PSF, loading probability and imaging confusion matrix.'), text('路径、波形哈希、移动后生存/温度和失败分类。', 'Paths, waveform hashes, post-move survival/temperature and failure classes.')],
    milestone: text('稳定生成并复核一个可重复的无缺陷 Yb 光镊寄存器', 'Stable generation and verification of a repeatable defect-free Yb tweezer register'),
    acceptance: [text('装载与温度保持跨天基线，且压力/RGA 不主导波动。', 'Loading and temperature remain within cross-day baselines without pressure/RGA dominating.'), text('成像 FP、FN、损失和邻站点串扰分别低于预算。', 'Imaging FP, FN, loss and neighbor crosstalk each remain below budget.'), text('重排同时报告填充率、移动数、周期、生存和温升。', 'Rearrangement reports filling, moves, cycle time, survival and heating together.')],
    theoryToExperiment: text('理论提供散射力、偶极势、阱频和轨迹加热模型；实验用温度、阱频和逐路径数据锁定参数。', 'Theory provides scattering, dipole-potential, trap-frequency and transport-heating models; experiment locks parameters with temperature, trap spectra and path-resolved data.'),
  },
  'qubit-encodings': {
    principle: text('171Yb 的 I=1/2 核自旋给出最小计算基，1S0 与 3P0 两个 J=0 流形可承担存储与操作。完整编码必须同时指定磁量子数、偏置场、光镊偏振、映射脉冲和读出规则。', 'The I=1/2 nuclear spin of 171Yb supplies a minimal basis, while J=0 1S0 and 3P0 manifolds support storage and operations. A complete encoding specifies magnetic states, bias field, tweezer polarization, mapping pulses and readout rules.'),
    equations: [{ expression: String.raw`H_q/\hbar=\frac{1}{2}[\Omega_x(t)\sigma_x+\Omega_y(t)\sigma_y+\delta(t)\sigma_z],\quad\delta=\delta_B+\delta_{\rm AC}+\delta_{\rm LO}`, explanation: text('横向控制决定旋转，纵向项汇集磁移、差分光移和本振失谐。', 'Transverse terms drive rotations while the longitudinal term combines magnetic, differential-light and LO detuning.') }],
    instruments: [
      apparatus('三轴线圈与低噪声电流源', 'Three-axis coils and low-noise sources', '定义量子化轴与核自旋劈裂。', 'Define quantization axis and nuclear-spin splitting.', '场矩阵、均匀性、电流噪声和热漂。', 'Field matrix, uniformity, current noise and thermal drift.'),
      apparatus('578 nm 钟激光与相位稳定传输', '578 nm clock laser and phase-stable delivery', '执行 1S0↔3P0 映射。', 'Drive 1S0-to-3P0 mapping.', 'Allan 偏差、拍频、末端相位、功率与 Rabi。', 'Allan deviation, beat note, delivered phase, power and Rabi.'),
      apparatus('RF/微波与状态选择读出', 'RF/microwave and state-selective readout', '旋转核自旋并映射到亮/暗结果。', 'Rotate nuclear spin and map to bright/dark outcomes.', '脉冲面积、相位、泄漏、往返映射和 SPAM。', 'Pulse area, phase, leakage, round-trip mapping and SPAM.'),
    ],
    procedure: [text('通过光抽运/选择性清除制备一个核自旋态，建立纯度与损失基线。', 'Prepare one nuclear-spin state by optical pumping/selective removal and establish purity/loss.'), text('扫描偏置场和 RF/光学频率，建立劈裂、选择定则与旁路谱。', 'Scan bias field and RF/optical frequency to map splitting, selection rules and spectators.'), text('完成 Rabi、Ramsey、echo 和站点扫描，分离失谐、幅度不均匀与低频噪声。', 'Run Rabi, Ramsey, echo and site scans to separate detuning, amplitude inhomogeneity and low-frequency noise.'), text('执行 1S0→3P0→1S0 往返，并区分泄漏、损失与读出错误。', 'Run 1S0-to-3P0-to-1S0 round trips and separate leakage, loss and readout error.')],
    outputs: [text('计算基、量子化轴、参考相位和符号约定。', 'Computational basis, quantization axis, reference phase and sign convention.'), text('磁场地图、Rabi/Ramsey/echo 后验和站点分布。', 'Field map, Rabi/Ramsey/echo posteriors and site distributions.'), text('映射矩阵、泄漏/损失/SPAM 分解和重标阈值。', 'Mapping matrix, leakage/loss/SPAM decomposition and recalibration thresholds.')],
    milestone: text('获得可逆、相位可追踪并跨站点一致的核自旋—钟态接口', 'A reversible, phase-traceable and site-uniform nuclear-spin/clock-state interface'),
    acceptance: [text('模型预测留出功率、站点和自由演化时间。', 'The model predicts held-out powers, sites and free-evolution times.'), text('往返映射同时满足保真、泄漏、损失和相位预算。', 'Round-trip mapping meets fidelity, leakage, loss and phase budgets together.'), text('重启后从已保存参考恢复相位，不依赖人工调相。', 'Phase is restored from saved references after restart without manual tuning.')],
    theoryToExperiment: text('理论明确多能级基底、选择定则和差分极化率；实验提供偏振、磁场、站点谱和映射矩阵。', 'Theory defines multilevel basis, selection rules and differential polarizability; experiment supplies polarization, field, site spectra and mapping matrices.'),
  },
  'controlled-phase': {
    principle: text('阻塞门要求四个计算基分支在同一脉冲下经历不同 Rydberg 通道，并在门末返回计算子空间、获得目标条件相位。有限阻塞、Doppler、激光相噪、衰变和旁路态共同定义通道。', 'A blockade gate requires four computational branches to traverse different Rydberg pathways under one pulse and return to the code space with the target conditional phase. Finite blockade, Doppler, laser phase noise, decay and spectators jointly define the channel.'),
    equations: [{ expression: String.raw`H/\hbar=\sum_{j=a,b}\left[\frac{\Omega_j(t)}{2}e^{i\phi_j(t)}|r_j\rangle\langle1_j|+\mathrm{h.c.}-\Delta_j(t)n_j\right]+V_{ab}n_an_b`, explanation: text('Ω、φ、Δ 和 V 必须来自原子面波形与本机双原子数据；候选 C6 只能产生灵敏度范围。', 'Ω, φ, Δ and V require atom-plane waveforms and local two-atom data; candidate C6 values support sensitivity ranges only.') }],
    instruments: [
      apparatus('302 nm 激发链与末端监测', '302 nm excitation and endpoint monitor', '产生并交付相干 Rydberg 光。', 'Generate and deliver coherent Rydberg light.', '转换效率、锁误差、相噪、末端功率/光斑/偏振。', 'Conversion, lock error, phase noise and delivered power/spot/polarization.'),
      apparatus('AWG/FPGA 与 AOM/EOM', 'AWG/FPGA and AOM/EOM', '执行幅度、相位、失谐和触发序列。', 'Execute amplitude, phase, detuning and triggers.', '实际光脉冲、延迟、过冲、相位瞬态和版本。', 'Delivered optical pulse, delay, overshoot, phase transient and version.'),
      apparatus('双原子阵列与状态选择读出', 'Two-atom array and state-selective readout', '测阻塞、条件相位、Bell 奇偶和失败类型。', 'Measure blockade, conditional phase, Bell parity and failures.', '逐基态计数、距离/角度、损失、泄漏与 SPAM。', 'Basis-resolved counts, distance/angle, loss, leakage and SPAM.'),
    ],
    procedure: [text('低功率单原子谱学锁定目标态、偏振、磁场和旁路态。', 'Use low-power single-atom spectroscopy to lock target state, polarization, field and spectators.'), text('扫描单原子时间、功率和失谐，联合拟合 Rabi、线宽、光移、损失与泄漏。', 'Scan single-atom duration, power and detuning; jointly fit Rabi, linewidth, light shift, loss and leakage.'), text('改变原子间距/角度，测双激发抑制、谱移和条件相位，得到 V(R,θ)。', 'Vary separation/angle to measure double-excitation suppression, spectral shift and conditional phase, obtaining V(R,θ).'), text('依次执行真值表、Ramsey 条件相位、Bell 奇偶和重复门。', 'Run truth table, Ramsey conditional phase, Bell parity and repeated gates in order.'), text('跨站点、跨天和不同并行密度复测相关错误与漂移。', 'Repeat across sites, days and parallel density to map correlated errors and drift.')],
    outputs: [text('单原子模型参数与原始光谱/Rabi 数据。', 'Single-atom model parameters and raw spectra/Rabi data.'), text('V(R,θ)、阻塞不确定度和缺失张量清单。', 'V(R,θ), blockade uncertainty and missing-tensor register.'), text('无条件/存活条件指标、损失、泄漏、SPAM 和条件相位。', 'Unconditional/survival-conditioned metrics, loss, leakage, SPAM and conditional phase.')],
    milestone: text('获得可跨站点重复、误差定义锁定的两原子受控相位通道', 'A site-repeatable two-atom controlled-phase channel with locked error definitions'),
    acceptance: [text('门末各分支返回计算子空间，局域相位修正规则预先声明。', 'All branches return to the code space with predeclared local-phase corrections.'), text('阻塞、衰变、Doppler、控制、损失和泄漏不重复计数。', 'Blockade, decay, Doppler, control, loss and leakage are not double counted.'), text('跨天和并行密度结果满足预算，不只保留单次最佳数据。', 'Cross-day and parallel-density results meet budgets, not only one best dataset.')],
    theoryToExperiment: text('理论交付多原子模型、灵敏度、硬件滤波后波形和下一项区分性测量；实验返回原始时序与条件结果。', 'Theory delivers a many-atom model, sensitivities, hardware-filtered waveforms and the next discriminating measurement; experiment returns raw timing and conditional outcomes.'),
  },
}
