import type { WikiEntry } from './wikiTypes'
import { diagnostic, principle, source, spec, step, t } from './wikiContentHelpers'

export const physicsWikiEntries: WikiEntry[] = [
  {
    id: 'rabi-frequency', term: t('Rabi 频率', 'Rabi frequency'),
    aliases: ['Rabi 频率', 'Rabi frequency', 'Rabi rate', '拉比频率'], category: 'physics',
    summary: t('相干驱动在两个量子态之间产生布居旋转的角频率；它把激光/微波场幅度和跃迁矩阵元连接到门时间。', 'The angular rate of coherent population rotation between two states, connecting field amplitude and transition matrix element to gate time.'),
    role: t('标定单比特旋转、钟态映射和 Rydberg π 脉冲，并诊断站点功率、偏振、失谐和相位不均匀。', 'Calibrates single-qubit rotations, clock-state mapping and Rydberg π pulses while diagnosing site power, polarization, detuning and phase inhomogeneity.'),
    principles: [
      principle('场—原子耦合', 'Field-atom coupling', '电偶极近似下，Rabi 频率由电场复振幅与跃迁偶极矩的内积决定；偏振分量、Clebsch–Gordan 系数、超精细混合和两光子中间态都必须包含。', 'In the electric-dipole approximation, Rabi frequency is the inner product of complex electric field and transition dipole. Polarization, angular coefficients, hyperfine mixing and two-photon intermediate states must be included.'),
      principle('失谐驱动与广义频率', 'Detuned drive and generalized frequency', '非零失谐时旋转轴倾斜，振荡频率变为 ΩR=sqrt(Ω²+Δ²)，最大转移小于 1。只拟合振荡周期而忽略对比度会把失谐误当作更强耦合。', 'With detuning, the rotation axis tilts, the observed frequency becomes sqrt(Ω²+Δ²), and maximum transfer is below one. Fitting period without contrast can mistake detuning for stronger coupling.')
    ],
    equations: [{ expression: String.raw`\Omega=\frac{\mathbf d\!\cdot\!\mathbf E}{\hbar},\qquad P_e(t)=\frac{\Omega^2}{\Omega^2+\Delta^2}\sin^2\!\left(\frac{\sqrt{\Omega^2+\Delta^2}\,t}{2}\right)`, explanation: t('第一式给出耦合，第二式是理想两能级常参数结果；衰减、泄漏、运动平均和 SPAM 必须在实际拟合中显式加入。', 'The first gives coupling and the second ideal two-level dynamics; decay, leakage, motion averaging and SPAM must be explicit in real fits.') }],
    workflow: [
      step('先锁定共振', 'Lock resonance first', '低功率扫频或 Ramsey 测中心，记录光移、磁场和锁频状态。', 'Find the center with low-power spectroscopy or Ramsey and log light shift, field and lock state.', '带不确定度的零失谐参考。', 'Zero-detuning reference with uncertainty.'),
      step('扫描脉冲时间', 'Scan pulse time', '固定功率采集多个周期，随机化扫描顺序并保留原始亮/暗/损失计数。', 'Acquire multiple periods at fixed power, randomize scan order and retain raw bright/dark/loss counts.', 'Ω、衰减包络、偏置和 SPAM 后验。', 'Posterior for Ω, decay envelope, offset and SPAM.'),
      step('功率标度检查', 'Check power scaling', '扫描末端功率验证 Ω∝sqrt(P)，偏离时检查饱和、模式和标定。', 'Sweep delivered power and verify Ω∝sqrt(P); inspect saturation, mode and calibration on deviation.', '功率到 Rabi 的工作 LUT。', 'Operating power-to-Rabi LUT.'),
      step('逐站点/跨天复测', 'Repeat by site and day', '绘制 Ω、对比度和共振频率的空间与时间分布。', 'Map Ω, contrast and resonance over sites and time.', '均匀性、漂移率和重标定阈值。', 'Uniformity, drift rate and recalibration threshold.')
    ],
    specifications: [
      spec('脉冲面积误差', 'Pulse-area error', '直接产生旋转角误差。', 'Directly creates rotation-angle error.', '从功率、时间和链路响应联合传播。', 'Propagate jointly from power, duration and chain response.'),
      spec('站点均匀性', 'Site uniformity', '并行门需共享可容忍的 Ω 分布。', 'Parallel gates need a tolerable Ω distribution.', '报告均值、尾部和空间相关，而非单点最佳值。', 'Report mean, tails and spatial correlation, not one best site.'),
      spec('相位参考', 'Phase reference', '决定旋转轴和 Ramsey 相位。', 'Sets rotation axis and Ramsey phase.', '触发、RF、光路和重启后相位均需验证。', 'Verify trigger, RF, optical path and post-restart phase.'),
      spec('模型维度', 'Model dimension', '旁路态会让两能级拟合产生偏差。', 'Spectator states bias a two-level fit.', '用残差、功率标度和偏振扫描决定是否升级模型。', 'Use residuals, power scaling and polarization scans to decide model expansion.')
    ],
    comparison: [{ option: t('脉冲面积 Ωt', 'Pulse area Ωt'), strengths: t('理想共振两能级下直接给旋转角。', 'Directly gives rotation angle for ideal resonant two-level dynamics.'), limitations: t('失谐、包络、相位调制和多能级时不能只用一个面积。', 'Insufficient with detuning, shaping, phase modulation or multilevel structure.'), useWhen: t('用于初始校准；高保真门用完整时间哈密顿量。', 'Use for initial calibration; use full time Hamiltonian for high-fidelity gates.') }],
    diagnostics: [
      diagnostic('振荡频率增大但转移对比度下降', 'Oscillation speeds up while transfer contrast falls', '失谐增大导致广义 Rabi 频率上升。', 'Increasing detuning raises generalized Rabi frequency.', '联合拟合频率与对比度，并独立扫频确认 Δ。', 'Fit frequency and contrast jointly and verify Δ spectroscopically.'),
      diagnostic('不同站点 Ω 与光功率不成平方根', 'Site Ω does not scale with square root of power', '偏振/矩阵元变化、光斑测量面错误、光移或饱和。', 'Polarization/matrix-element variation, wrong power plane, light shift or saturation.', '同时测 Stokes、原子面功率、共振中心和功率标度。', 'Measure Stokes, atom-plane power, resonance center and scaling together.')
    ],
    related: ['detuning', 'ac-stark-shift', 'ramsey', 'aom', 'awg', 'optical-tweezer'],
    sources: [source('Cohen-Tannoudji, Dupont-Roc and Grynberg, Atom-Photon Interactions (1992)', 'https://www.wiley.com/en-us/Atom+Photon+Interactions-p-9780471293361')],
  },
  {
    id: 'detuning', term: t('失谐', 'Detuning'),
    aliases: ['失谐', 'detuning', '频率失谐', 'laser detuning'], category: 'physics',
    summary: t('驱动角频率与原子跃迁角频率之差；其符号和随时间变化决定散射力、光移、选择性和旋转轴。', 'The drive angular frequency minus the atomic transition frequency; sign and time dependence set scattering force, light shifts, selectivity and rotation axis.'),
    role: t('控制 MOT 红失谐、Raman/钟态选择性、Rydberg 激发条件和鲁棒脉冲扫频。', 'Controls MOT red detuning, Raman/clock selectivity, Rydberg excitation and robust chirped pulses.'),
    principles: [principle('参考框架中的能量差', 'Energy offset in the rotating frame', '进入驱动旋转框架后，失谐成为激发态对角能量。实验中的有效失谐还包含 Doppler、Zeeman、AC Stark、相互作用位移和锁频误差。', 'In the drive rotating frame, detuning is the excited-state diagonal energy. Experimental effective detuning also includes Doppler, Zeeman, AC Stark, interaction shifts and lock error.')],
    equations: [{ expression: String.raw`\Delta_{\rm eff}(t)=\omega_L(t)-\omega_0-\mathbf k\!\cdot\!\mathbf v-\Delta_Z-\Delta_{\rm AC}-\Delta_{\rm int}`, explanation: t('各项必须使用同一符号约定和角频率/普通频率单位；混用 MHz 与 Mrad/s 是常见系统错误。', 'All terms require one sign convention and consistent angular/ordinary frequency units; mixing MHz and Mrad/s is a common systematic error.') }],
    workflow: [step('定义符号与单位', 'Define sign and units', '在序列和拟合中明确 Δ=ωL−ω0 或相反，并统一 2π。', 'State whether Δ=ωL−ω0 or the opposite and handle 2π consistently.', '实验控制与理论模型共用的参数定义。', 'Shared parameter definition for control and theory.'), step('独立测中心', 'Measure the center independently', '低功率、短时间扫频，外推到零功率并记录磁场。', 'Use low-power short spectroscopy, extrapolate to zero power and log field.', '裸跃迁中心与光移斜率。', 'Bare transition center and light-shift slope.'), step('分解有效失谐', 'Decompose effective detuning', '改变速度/温度、磁场、阱深和邻原子状态，分别提取各项。', 'Vary velocity/temperature, field, trap depth and neighbor state to extract terms.', '带相关性的 Δ 误差预算。', 'Correlated detuning error budget.')],
    specifications: [spec('锁频误差', 'Lock error', '进入 shot-to-shot 和慢漂失谐。', 'Enters shot-to-shot and slow detuning drift.', '同时记录误差信号、控制量和拍频。', 'Log error, control and beat note together.'), spec('Doppler 宽度', 'Doppler width', '决定门对温度和几何的敏感度。', 'Sets gate sensitivity to temperature and geometry.', '从本机温度与有效 k 传播，不用经验退相干替代。', 'Propagate from local temperature and effective k, not an empirical dephasing substitute.'), spec('空间光移分布', 'Spatial light-shift distribution', '导致站点共振不均匀。', 'Creates site resonance inhomogeneity.', '逐站点测中心并关联光镊强度/偏振。', 'Measure site centers and correlate with tweezer intensity/polarization.')],
    diagnostics: [diagnostic('扫频中心随功率线性移动', 'Spectral center shifts linearly with power', 'AC Stark 位移或伺服监测面功率相关误差。', 'AC Stark shift or power-dependent servo-plane error.', '多功率外推零功率并改变偏振/阱深。', 'Extrapolate several powers to zero and vary polarization/depth.'), diagnostic('同一失谐在不同扫描方向结果不同', 'Opposite scan directions give different detuning', '慢漂、热滞后、原子耗尽或伺服建立时间。', 'Slow drift, thermal hysteresis, atom depletion or servo settling.', '随机化顺序、双向交错并记录时间戳与控制量。', 'Randomize/interleave directions and log timestamp/control.')],
    related: ['rabi-frequency', 'ac-stark-shift', 'mot', 'ramsey', 'rydberg-blockade'],
    sources: [source('Cohen-Tannoudji, Dupont-Roc and Grynberg, Atom-Photon Interactions (1992)', 'https://www.wiley.com/en-us/Atom+Photon+Interactions-p-9780471293361')],
  },
  {
    id: 'ac-stark-shift', term: t('AC Stark 位移', 'AC Stark shift'),
    aliases: ['AC Stark 位移', 'AC Stark shift', '交流斯塔克位移', 'light shift', '光移'], category: 'physics',
    summary: t('非共振光场通过虚跃迁改变原子能级；差分位移既形成光镊势，也移动量子比特和 Rydberg 共振。', 'Off-resonant fields shift atomic levels through virtual transitions; differential shifts form traps and move qubit/Rydberg resonances.'),
    role: t('决定光镊深度、魔术条件、站点共振分布、相位积累和光致退相干。', 'Sets tweezer depth, magic conditions, site resonance distribution, accumulated phase and light-induced dephasing.'),
    principles: [principle('动态极化率', 'Dynamic polarizability', '能级位移由频率相关极化率和局部强度决定。Yb 两电子结构使标量、矢量、张量贡献和附近中间态很重要；不同电子态的差分极化率决定钟态或 Rydberg 映射是否对阱光敏感。', 'The shift follows frequency-dependent polarizability and local intensity. Yb two-electron structure makes scalar, vector, tensor terms and nearby intermediates important; differential polarizability determines trap sensitivity of clock or Rydberg mappings.')],
    equations: [{ expression: String.raw`\Delta E_i=-\frac{1}{2}\alpha_i(\omega)\langle E^2\rangle,\qquad \delta\omega_{ab}=\frac{\Delta E_b-\Delta E_a}{\hbar}`, explanation: t('第一式给单能级位移，第二式给跃迁频率的差分光移。精确系数依赖峰值/RMS 电场约定，必须与使用的极化率定义一致。', 'The first is a level shift and the second a differential transition shift. Exact factors depend on peak/RMS field conventions and must match the polarizability definition.') }],
    workflow: [step('功率分级光谱', 'Power-stepped spectroscopy', '在多个阱深或控制光功率下测跃迁中心，交错采样抑制漂移。', 'Measure transition centers at several trap/control powers with interleaving.', '差分光移斜率与非线性残差。', 'Differential-shift slope and nonlinear residual.'), step('偏振与磁场扫描', 'Scan polarization and field', '改变 Stokes 参数和量子化轴，分离标量/矢量/张量贡献。', 'Vary Stokes parameters and quantization axis to separate scalar/vector/tensor terms.', '极化率模型与偏振敏感度。', 'Polarizability model and polarization sensitivity.'), step('站点校正', 'Correct sites', '逐站点测共振或 Rabi 相位，用 SLM/AOD 权重和频率补偿。', 'Measure site resonance or Rabi phase and compensate through SLM/AOD weights or frequency.', '站点光移地图和补偿版本。', 'Site light-shift map and compensation version.')],
    specifications: [spec('差分极化率', 'Differential polarizability', '直接决定相位对强度噪声的敏感度。', 'Directly sets phase sensitivity to intensity noise.', '以本机态、波长、偏振和磁场测量。', 'Measure for local states, wavelength, polarization and field.'), spec('强度均匀与噪声', 'Intensity uniformity and noise', '产生静态失谐分布和动态退相干。', 'Create static detuning spread and dynamic dephasing.', '分别报告空间分布与 PSD。', 'Report spatial distribution and PSD separately.'), spec('魔术点稳定性', 'Magic-point stability', '零一阶差分光移可能对波长/偏振敏感。', 'Zero first-order differential shift may be sensitive to wavelength/polarization.', '测局部斜率、曲率和漂移余量。', 'Measure local slope, curvature and drift margin.')],
    comparison: [{ option: t('DC Stark / Zeeman 位移', 'DC Stark / Zeeman shift'), strengths: t('可用静电或磁场独立调谐。', 'Allows independent tuning with electric or magnetic fields.'), limitations: t('引入电极、线圈噪声和空间梯度。', 'Adds electrode/coil noise and gradients.'), useWhen: t('通过不同控制量扫描区分光移、磁移和电场位移。', 'Use independent scans to separate optical, magnetic and electric shifts.') }],
    diagnostics: [diagnostic('Ramsey 相干随阱深增加变差', 'Ramsey coherence worsens with trap depth', '差分光移不均匀、强度噪声或运动采样。', 'Differential-shift inhomogeneity, intensity noise or motional sampling.', '测站点中心、强度 PSD、温度和 echo 改善量。', 'Measure site centers, intensity PSD, temperature and echo improvement.'), diagnostic('相同功率不同偏振共振变化', 'Resonance changes with polarization at fixed power', '矢量/张量极化率或窗口双折射。', 'Vector/tensor polarizability or window birefringence.', '在原子面测 Stokes，并旋转量子化轴验证对称性。', 'Measure atom-plane Stokes and rotate quantization axis to test symmetry.')],
    related: ['optical-tweezer', 'detuning', 'rabi-frequency', 'ramsey'],
    sources: [source('Grimm, Weidemüller and Ovchinnikov, Advances in Atomic, Molecular and Optical Physics 42, 95–170 (2000)', 'https://doi.org/10.1016/S1049-250X(08)60186-X')],
  },
  {
    id: 'rydberg-blockade', term: t('Rydberg 阻塞', 'Rydberg blockade'),
    aliases: ['Rydberg 阻塞', 'Rydberg blockade', '里德堡阻塞', 'blockade radius'], category: 'physics',
    summary: t('一个原子进入强相互作用 Rydberg 态后，使邻原子的双激发态移出激光线宽，从而产生条件动力学。', 'Exciting one atom to a strongly interacting Rydberg state shifts a neighbor’s double-excitation state out of the laser linewidth, creating conditional dynamics.'),
    role: t('将局域激光控制转换为两原子条件相位、并行纠缠门和可编程相互作用。', 'Converts local optical control into two-atom conditional phase, parallel entangling gates and programmable interactions.'),
    principles: [
      principle('双激发能移', 'Double-excitation shift', '远离 Förster 共振时常以 van der Waals 势 C6/R6 描述；近共振或简并多通道时需对偶极—偶极耦合矩阵对角化。Yb 的多通道、角度和量子数依赖不能用单一 C6 覆盖所有几何。', 'Away from Förster resonance, a C6/R6 van der Waals potential often applies. Near resonances or degenerate channels, the dipole-dipole matrix must be diagonalized. Yb multichannel, angular and quantum-number dependence cannot always be reduced to one C6.'),
      principle('有限阻塞误差', 'Finite-blockade error', '当相互作用位移 V 仅有限大于 Ω 时，双激发布居约按 (Ω/V)² 泄漏，并伴随条件相位偏差。增大 Ω 缩短衰变时间却加重阻塞误差，形成门速率权衡。', 'When V is only finitely larger than Ω, double excitation scales roughly as (Ω/V)² and conditional phase shifts. Larger Ω shortens decay exposure but worsens blockade error, creating a gate-speed tradeoff.')
    ],
    equations: [{ expression: String.raw`V(R)=C_6/R^6,\qquad R_b=\left(|C_6|/\hbar\Omega_{\rm eff}\right)^{1/6}`, explanation: t('阻塞半径是相互作用能移等于有效激发线宽/耦合的尺度。它不是硬边界，实际门还依赖失谐、脉冲形状、角度、多能级和运动。', 'The blockade radius is the scale where interaction shift equals effective excitation width/coupling. It is not a hard boundary; gates also depend on detuning, pulse shape, angle, multilevel structure and motion.') }],
    workflow: [
      step('单原子谱学', 'Single-atom spectroscopy', '锁定目标 Rydberg 态、偏振、磁场、Rabi、寿命和旁路态。', 'Lock target Rydberg state, polarization, field, Rabi rate, lifetime and spectators.', '单原子哈密顿量与线宽预算。', 'Single-atom Hamiltonian and linewidth budget.'),
      step('双原子距离扫描', 'Two-atom distance scan', '改变间距和角度，测双激发抑制、谱线位移与条件相位。', 'Vary separation and angle; measure double-excitation suppression, spectral shift and conditional phase.', 'V(R,θ) 数据与模型后验。', 'V(R,θ) data and model posterior.'),
      step('门序列分层验收', 'Layer gate acceptance', '依次测真值表、Ramsey 条件相位、Bell 奇偶和重复门。', 'Measure truth table, Ramsey conditional phase, Bell parity and repeated gates in sequence.', '计算保真度、损失、泄漏和相位分开报告。', 'Separate computational fidelity, loss, leakage and phase.'),
      step('并行与跨天测试', 'Test parallelism and days', '改变同时门数、邻居状态、站点和日期，寻找相关串扰。', 'Vary concurrent gates, neighbor states, sites and days to find correlated crosstalk.', '并行密度相关通道和重标定阈值。', 'Parallel-density-dependent channel and recalibration threshold.')
    ],
    specifications: [
      spec('V/Ω 比', 'V/Ω ratio', '控制有限阻塞泄漏和相位。', 'Controls finite-blockade leakage and phase.', '从双原子数据而非候选 C6 单独估计。', 'Estimate from two-atom data rather than candidate C6 alone.'),
      spec('Rydberg 寿命/退相干', 'Rydberg lifetime/decoherence', '限制可积累门时间。', 'Limits usable gate duration.', '区分自然寿命、黑体、激光相噪和损失。', 'Separate natural, blackbody, laser phase noise and loss.'),
      spec('Doppler 与温度', 'Doppler and temperature', '有效波矢把运动转换为失谐噪声。', 'Effective wavevector converts motion to detuning noise.', '用本机温度和几何进入模型。', 'Use local temperature and geometry in the model.'),
      spec('旁路耦合', 'Spectator coupling', '邻近 Rydberg/中间态产生泄漏和 AC Stark。', 'Nearby Rydberg/intermediate states create leakage and AC Stark shifts.', '偏振、磁场和功率扫描验证多能级模型。', 'Validate multilevel model with polarization, field and power scans.')
    ],
    comparison: [{ option: t('Rydberg dressing', 'Rydberg dressing'), strengths: t('低 Rydberg 占据下产生较弱、较长时间相互作用。', 'Provides weaker longer interactions with low Rydberg population.'), limitations: t('对失谐、散射和多体软核势更敏感。', 'Sensitive to detuning, scattering and many-body soft-core potentials.'), useWhen: t('适合模拟/连续相互作用；快速数字门常用直接阻塞。', 'Useful for analog/continuous interactions; fast digital gates often use direct blockade.') }],
    diagnostics: [
      diagnostic('双激发抑制强但 Bell 保真度低', 'Strong blockade but low Bell fidelity', '条件相位、单比特光移、Doppler、衰变或 SPAM，而非阻塞不足。', 'Conditional phase, local light shift, Doppler, decay or SPAM rather than weak blockade.', '分开测真值表、Ramsey 相位、损失/泄漏和奇偶振荡。', 'Separate truth table, Ramsey phase, loss/leakage and parity oscillation.'),
      diagnostic('阻塞随阵列方向变化', 'Blockade varies with array direction', '偶极相互作用张量、量子化轴、偏振或磁场混合。', 'Dipole interaction tensor, quantization axis, polarization or field mixing.', '旋转原子对方向和偏置场，对照完整角动量模型。', 'Rotate pair direction and bias field against a full angular-momentum model.')
    ],
    related: ['rabi-frequency', 'detuning', 'ac-stark-shift', 'leakage', 'erasure'],
    sources: [source('Saffman, Walker and Mølmer, Reviews of Modern Physics 82, 2313 (2010)', 'https://doi.org/10.1103/RevModPhys.82.2313')],
  },
  {
    id: 'ramsey', term: t('Ramsey 干涉', 'Ramsey interferometry'),
    aliases: ['Ramsey', 'Ramsey 干涉', 'Ramsey interferometry', 'Ramsey 序列'], category: 'measurement',
    summary: t('用两个相干 π/2 脉冲把自由演化相位转换为布居条纹，是测失谐、相干、光移和条件相位的核心工具。', 'Two coherent π/2 pulses convert free-evolution phase into population fringes, measuring detuning, coherence, light shifts and conditional phase.'),
    role: t('标定核自旋/钟态相干、磁场与光移噪声，并读取 Rydberg 门的条件相位。', 'Calibrates nuclear-spin/clock coherence, field and light-shift noise, and reads conditional phase of Rydberg gates.'),
    principles: [principle('相位到布居的干涉', 'Phase-to-population interference', '第一脉冲建立叠加态，自由演化积累相对相位，第二脉冲与可控分析相位干涉。条纹频率给平均失谐，包络包含准静态分布和动态噪声。', 'The first pulse creates a superposition, free evolution accumulates relative phase, and the second pulse interferes with a controlled analysis phase. Fringe frequency gives mean detuning; the envelope contains quasistatic spread and dynamic noise.')],
    equations: [{ expression: String.raw`P_1(T,\phi)=\frac{1}{2}\left[1+C(T)\cos(\Delta T+\phi+\phi_0)\right]`, explanation: t('C(T) 是相干包络，不应自动假设指数；不同噪声谱可产生高斯、指数或更复杂衰减。', 'C(T) is the coherence envelope and need not be exponential; different noise spectra produce Gaussian, exponential or more complex decay.') }],
    workflow: [step('校准两次 π/2', 'Calibrate both π/2 pulses', '先用 Rabi 扫描确认脉冲面积和相位轴。', 'Use Rabi scans to verify pulse area and phase axes.', '单脉冲误差与 SPAM 基线。', 'Single-pulse error and SPAM baseline.'), step('交错扫描 T 与分析相位', 'Interleave time and analysis phase', '随机化自由演化时间和末脉冲相位，保留逐 shot 环境量。', 'Randomize free-evolution time and final phase while retaining shot environment.', '条纹频率、相位和包络后验。', 'Posterior for fringe frequency, phase and envelope.'), step('echo/条件分支比较', 'Compare echo or conditional branches', '加入 echo 或邻原子门操作，差分提取低频噪声或条件相位。', 'Add echo or neighbor-gate operation and difference branches to extract low-frequency noise or conditional phase.', '噪声频段/条件相位及置信区间。', 'Noise-band or conditional-phase estimate with confidence.')],
    specifications: [spec('本振相位连续', 'Local-oscillator phase continuity', '本振噪声与原子退相干不可自动区分。', 'LO noise is not automatically distinguishable from atomic dephasing.', '共享参考并记录锁误差/拍频。', 'Share reference and log lock error/beat note.'), spec('自由演化时间戳', 'Free-evolution timestamp', '时序偏差直接转为相位。', 'Timing error directly becomes phase.', '测物理脉冲中心而非数字边沿。', 'Measure physical pulse centers, not digital edges.'), spec('拟合模型', 'Fit model', '错误包络会偏置 T2*。', 'Wrong envelope biases T2*.', '比较候选噪声模型和留出数据预测。', 'Compare noise models and held-out prediction.')],
    diagnostics: [diagnostic('条纹相位跨 shot 突跳', 'Fringe phase jumps between shots', '触发相位、本振重启、失锁或相位解缠错误。', 'Trigger phase, LO restart, unlock or phase-unwrapping error.', '按失锁位、波形版本和时间戳分组原始数据。', 'Group raw data by unlock flag, waveform version and timestamp.'), diagnostic('echo 大幅改善但 T2* 很短', 'Echo strongly improves a short T2*', '准静态磁场/光移不均匀主导。', 'Quasistatic field or light-shift inhomogeneity dominates.', '测空间分布、低频 PSD 和站点差分。', 'Measure spatial distribution, low-frequency PSD and site differences.')],
    related: ['rabi-frequency', 'detuning', 'ac-stark-shift', 'spam'],
    sources: [source('Ramsey, Molecular Beams (1956)', 'https://global.oup.com/academic/product/molecular-beams-9780198520214')],
  },
  {
    id: 'spam', term: t('态制备与测量误差', 'State-preparation and measurement error'), abbreviation: 'SPAM',
    aliases: ['SPAM', '态制备与测量误差', 'state-preparation and measurement error', '制备测量误差'], category: 'measurement',
    summary: t('量子态制备和读出分类引入的联合误差；它会污染 Rabi、Ramsey、真值表和门保真度，但不能简单从所有结果中标量相减。', 'Joint error from state preparation and readout classification; it contaminates Rabi, Ramsey, truth tables and gate metrics but cannot always be removed by scalar subtraction.'),
    role: t('建立亮/暗/损失/泄漏的混淆矩阵，使原子物理通道与读出判据在同一概率模型中可区分。', 'Builds a bright/dark/loss/leakage confusion matrix so atomic channels and readout decisions are separable in one probabilistic model.'),
    principles: [principle('经典混淆与量子反作用', 'Classical confusion and quantum backaction', '阈值分类产生 FP/FN；状态选择推走、光抽运和成像散射还会改变真实态或造成损失。读出不是纯粹的标签噪声，必须说明测量前后定义。', 'Thresholding creates false positives/negatives; push-out, optical pumping and imaging scattering can change the state or cause loss. Readout is not always pure label noise, so pre/post-measurement definitions matter.')],
    equations: [{ expression: String.raw`\mathbf p_{\rm obs}=M_{\rm SPAM}\mathbf p_{\rm true},\qquad (M_{ij}=P(\text{outcome }i\mid\text{prepared }j))`, explanation: t('线性混淆矩阵只在制备集合完备、时间稳定且不隐藏条件化时成立；直接求逆会放大统计噪声，宜用受约束似然或贝叶斯传播。', 'A linear confusion matrix applies only for complete preparations, temporal stability and explicit conditioning. Direct inversion amplifies noise; constrained likelihood or Bayesian propagation is preferable.') }],
    workflow: [step('独立制备参考态', 'Prepare reference states independently', '交错制备 |0⟩、|1⟩、空站点和可识别泄漏/损失参考。', 'Interleave |0>, |1>, empty and identifiable leakage/loss references.', '带原始帧的标定数据集。', 'Calibration set with raw frames.'), step('构建站点混淆矩阵', 'Build site confusion matrices', '联合 PSF/ROI 计数和状态选择操作，估计 FP、FN、损失和泄漏。', 'Combine PSF/ROI counts and state-selective operations to estimate FP, FN, loss and leakage.', '逐站点矩阵、置信区间和漂移。', 'Site matrices, intervals and drift.'), step('传播而非删除', 'Propagate rather than delete', '在门/相干拟合似然中加入 SPAM 参数或联合后验，不把最佳值直接扣除。', 'Include SPAM in gate/coherence likelihoods or joint posterior rather than subtracting a point estimate.', '原始指标、条件指标和校正指标并列。', 'Raw, conditioned and corrected metrics side by side.')],
    specifications: [spec('FP/FN 分离', 'FP/FN separation', '两者对逻辑通道影响不同。', 'They affect logical channels differently.', '分别报告且按站点/时间分层。', 'Report separately by site and time.'), spec('损失与暗态', 'Loss versus dark state', '暗结果可能是 |1⟩、泄漏或原子不存在。', 'A dark outcome may be |1>, leakage or no atom.', '增加复核成像或状态选择步骤区分。', 'Use verification imaging or selective steps to distinguish.'), spec('标定漂移', 'Calibration drift', '固定阈值会跨天偏置。', 'Fixed thresholds bias across days.', '设置哨兵 shot 和重新标定触发。', 'Use sentinel shots and recalibration triggers.')],
    comparison: [{ option: t('后选择存活原子', 'Postselect surviving atoms'), strengths: t('可分离部分损失机制。', 'Separates some loss mechanisms.'), limitations: t('改变统计总体，可能夸大条件保真度。', 'Changes the population and can inflate conditional fidelity.'), useWhen: t('必须同时报告无条件结果、存活率和选择规则。', 'Always report unconditional result, survival and selection rule together.') }],
    diagnostics: [diagnostic('校正后保真度超过物理范围', 'Corrected fidelity exceeds physical range', '直接矩阵求逆、统计噪声或错误的 SPAM 独立假设。', 'Direct inversion, statistical noise or false SPAM-independence assumption.', '改用受约束似然并检查条件数与后验预测。', 'Use constrained likelihood and inspect condition number/posterior prediction.'), diagnostic('阈值不变但误判上升', 'Misclassification rises at fixed threshold', 'PSF、背景、相机增益、原子散射或损失变化。', 'PSF, background, camera gain, scattering or loss changed.', '比较原始帧分布和独立生存测量，不只看阈值输出。', 'Compare raw-frame distributions and independent survival, not threshold output alone.')],
    related: ['scientific-camera', 'psf', 'ramsey', 'leakage', 'erasure'],
    sources: [source('Merkel et al., Physical Review A 87, 062119 (2013)', 'https://doi.org/10.1103/PhysRevA.87.062119')],
  },
  {
    id: 'leakage', term: t('泄漏误差', 'Leakage error'),
    aliases: ['泄漏', '泄漏误差', 'leakage', 'leakage error'], category: 'architecture',
    summary: t('量子态离开定义的计算子空间但原子可能仍存在；后续门对泄漏态的作用通常不同于 Pauli 错误。', 'The state leaves the computational subspace while the atom may remain; subsequent gates generally act differently on leakage than on Pauli errors.'),
    role: t('区分旁路能级占据、Rydberg 残留、钟态映射失败与真正原子损失，并决定是否需要泄漏清除或擦除标记。', 'Separates spectator-state population, residual Rydberg excitation and clock-mapping failure from atom loss, determining leakage removal or erasure marking.'),
    principles: [principle('子空间外动力学', 'Dynamics outside the code space', '泄漏态不再服从预期两能级门；它可能在后续周期返回、积累相关相位或传播错误。只把最终暗结果计作 Pauli 错误会隐藏时间相关性。', 'A leaked state no longer follows the intended two-level gate; it may return later, accumulate correlated phase or propagate faults. Counting only final darkness as Pauli error hides temporal correlation.')],
    equations: [{ expression: String.raw`p_{\rm leak}=1-\mathrm{Tr}(P_{\rm comp}\rho),\qquad P_{\rm comp}=|0\rangle\langle0|+|1\rangle\langle1|`, explanation: t('泄漏是计算子空间投影外的布居；若存在原子损失，需要把真空态作为另一个正交结果单独处理。', 'Leakage is population outside the computational projector; atom loss requires a separate orthogonal vacuum outcome.') }],
    workflow: [step('定义完整结果空间', 'Define full outcome space', '列出计算态、可解析泄漏态、Rydberg/亚稳态和真空态。', 'List computational, resolvable leakage, Rydberg/metastable and vacuum states.', '测量 POVM 与分类字典。', 'Measurement POVM and classification dictionary.'), step('加入泄漏敏感脉冲', 'Add leakage-sensitive pulses', '用 repump、shelving、push-out 或选择性光谱把不同子空间映射到可区分结果。', 'Use repump, shelving, push-out or selective spectroscopy to map subspaces to distinguishable outcomes.', '泄漏检测混淆矩阵。', 'Leakage-detection confusion matrix.'), step('测时间相关', 'Measure temporal correlation', '重复门/空闲周期并在不同周期检查泄漏和返回。', 'Repeat gates/idles and check leakage plus return at different cycles.', '泄漏产生、持续和回流概率。', 'Leakage generation, persistence and seepage probabilities.')],
    specifications: [spec('泄漏率与回流率', 'Leakage and seepage rates', '共同决定多周期稳态。', 'Jointly determine multicycle steady state.', '从重复周期而非单门末态估计。', 'Estimate from repeated cycles, not one gate end.'), spec('检测召回与误报', 'Detection recall and false positives', '决定能否转换为擦除。', 'Set whether leakage can become erasure.', '与残余未标记 Pauli 错误一起报告。', 'Report with residual unflagged Pauli error.'), spec('清除代价', 'Leakage-removal cost', '复位会增加时间、散射和邻站点串扰。', 'Reset adds time, scattering and neighbor crosstalk.', '在完整 QEC 周期中评估。', 'Evaluate in full QEC cycle.')],
    comparison: [{ option: t('原子损失', 'Atom loss'), strengths: t('空站点常可直接成像并定位。', 'Empty sites are often directly imageable and located.'), limitations: t('补原子、移动和周期中断有额外代价。', 'Replacement, movement and cycle interruption add cost.'), useWhen: t('分析中保持“存在但泄漏”和“原子不存在”两个结果。', 'Keep present-but-leaked and absent-atom outcomes separate.') }],
    diagnostics: [diagnostic('门后暗结果但复核成像仍有原子', 'Dark gate result but atom remains in verification image', '泄漏、错误 shelving/repump 或状态选择读出失败。', 'Leakage, incorrect shelving/repump or state-selective readout failure.', '改变 repump/选择性脉冲并做完整态映射。', 'Vary repump/selective pulses and perform full state mapping.'), diagnostic('重复门误差非线性增长', 'Repeated-gate error grows nonlinearly', '泄漏积累、回流或慢漂相关。', 'Leakage accumulation, seepage or slow correlated drift.', '在不同循环插入泄漏检测，拟合多状态 Markov/量子通道。', 'Insert leakage checks at different cycles and fit a multistate Markov/quantum channel.')],
    related: ['spam', 'erasure', 'rydberg-blockade'],
    sources: [source('Wood and Gambetta, Physical Review A 97, 032306 (2018)', 'https://doi.org/10.1103/PhysRevA.97.032306')],
  },
  {
    id: 'erasure', term: t('擦除错误', 'Erasure error'),
    aliases: ['擦除', '擦除错误', 'erasure', 'erasure error', '擦除转换'], category: 'architecture',
    summary: t('错误位置被经典标记的通道；已知位置通常比未知 Pauli 错误更容易被解码器纠正，但标记并不保证错误类型完全已知。', 'A channel whose fault location is classically flagged. Located faults are generally easier to decode than unknown Pauli errors, but a flag does not imply the complete error type is known.'),
    role: t('把可探测的 Yb 亚稳态、泄漏或原子损失转化为解码器输入，并评估其是否抵消检测与补原子的额外开销。', 'Converts detectable Yb metastable states, leakage or atom loss into decoder input and tests whether this outweighs detection and replacement overhead.'),
    principles: [principle('已知位置的条件通道', 'Located conditional channel', '擦除事件给出位置/时间标签，解码器可在该条件下更新。实际实验还存在漏报、误报和擦除事件中的残余相干/Pauli 分量，因此必须使用联合通道。', 'An erasure event supplies a location/time flag for conditional decoding. Real experiments also have false negatives, false positives and residual coherent/Pauli components within flagged events, requiring a joint channel.')],
    equations: [{ expression: String.raw`\mathcal N(\rho)=(1-p_f)\mathcal N_0(\rho)\otimes|0\rangle\langle0|_f+p_f\mathcal N_f(\rho)\otimes|1\rangle\langle1|_f`, explanation: t('f 是经典标记；未标记通道 N0 和已标记通道 Nf 都需要实验表征。只给 p_f 不能预测逻辑性能。', 'f is the classical flag. Both unflagged channel N0 and flagged channel Nf need characterization; p_f alone cannot predict logical performance.') }],
    workflow: [step('定义可标记物理事件', 'Define flaggable physical events', '明确哪些衰变、泄漏、损失或状态映射产生可观测标签。', 'State which decay, leakage, loss or mapping events produce observable flags.', '事件—测量—标记映射表。', 'Event-measurement-flag map.'), step('标定标签混淆矩阵', 'Calibrate flag confusion', '用已知事件样本测召回、误报、时间定位和站点串扰。', 'Use known-event samples to measure recall, false positives, timing localization and site crosstalk.', 'P(flag|event) 及不确定度。', 'P(flag|event) with uncertainty.'), step('表征条件通道', 'Characterize conditional channels', '分别对标记和未标记 shot 做计算态、泄漏、损失和 Pauli/相干误差分析。', 'Analyze computational, leakage, loss and Pauli/coherent errors separately for flagged and unflagged shots.', 'N0、Nf 和空间/时间相关。', 'N0, Nf and spatial/temporal correlations.'), step('进入完整逻辑周期', 'Insert into full logical cycle', '包含检测时间、补原子、调度冲突和解码延迟，比较逻辑错误率。', 'Include detection time, replacement, scheduling conflicts and decoding latency; compare logical error.', '净逻辑收益与适用工作区。', 'Net logical benefit and operating regime.')],
    specifications: [spec('召回率', 'Recall', '漏报变成更危险的未标记错误。', 'False negatives become more dangerous unflagged faults.', '按事件类型、站点和时间分层。', 'Stratify by event type, site and time.'), spec('误报率', 'False-positive rate', '无故删除可靠量子比特并增加补原子。', 'Unnecessarily removes reliable qubits and adds replacement.', '在真实基础率下报告 precision 与 recall。', 'Report precision and recall at real base rates.'), spec('检测/复位时间', 'Detection/reset time', '增加退相干和调度冲突。', 'Adds dephasing and scheduling conflicts.', '以端到端物理响应而非数字指令计时。', 'Time end-to-end physical response, not digital commands.'), spec('残余未标记通道', 'Residual unflagged channel', '最终决定阈值是否真正改善。', 'Ultimately determines threshold improvement.', '与擦除率一起输入解码器。', 'Feed to decoder together with erasure rate.')],
    comparison: [{ option: t('未知 Pauli 错误', 'Unknown Pauli error'), strengths: t('无需额外检测步骤。', 'Requires no extra detection step.'), limitations: t('位置未知，解码组合更大。', 'Unknown location enlarges decoding ambiguity.'), useWhen: t('比较必须在相同完整周期和相同条件化规则下进行。', 'Compare under the same full cycle and conditioning rules.') }],
    diagnostics: [diagnostic('擦除率提高但逻辑性能未改善', 'Higher erasure fraction does not improve logical performance', '漏报残余、误报、检测延迟、相关故障或补原子开销。', 'Residual false negatives, false positives, detection latency, correlated faults or replacement overhead.', '把条件通道与时序开销一起输入周期模拟，做逐项消融。', 'Feed conditional channels and timing into cycle simulation and ablate each contribution.'), diagnostic('标记事件集中在特定站点', 'Flags cluster on specific sites', '光强/偏振、成像阈值、局部真空或控制串扰。', 'Intensity/polarization, imaging threshold, local vacuum or control crosstalk.', '与站点 Rabi、PSF、阱频、邻居操作和压力状态关联。', 'Correlate with site Rabi, PSF, trap frequency, neighbor operations and vacuum state.')],
    related: ['leakage', 'spam', 'rydberg-blockade', 'fpga'],
    sources: [source('Wu et al., Nature 604, 457–462 (2022)', 'https://doi.org/10.1038/s41586-022-04566-8')],
  },
]
