import type { Language } from '../../types/content'
import WikiText from '../wiki/WikiText'
import CoreQuestionFrame from './CoreQuestionFrame'
import MapEquation from './MapEquation'
import { gateLoopNodes } from './coreQuestionData'

export default function GateImplementationLoop({ language }: { language: Language }) {
  return (
    <CoreQuestionFrame
      id="core-gate-loop"
      eyebrow={{ zh: '目标幺正 · 哈密顿量 · 实测通道', en: 'TARGET UNITARY · HAMILTONIAN · MEASURED CHANNEL' }}
      title={{ zh: '量子门怎样从理论走到实验', en: 'How a quantum gate moves from theory to experiment' }}
      thesis={{
        zh: '量子门不是脉冲名称，而是受控哈密顿量在给定时间内生成的量子通道；实验必须反演该通道并把偏差反馈到模型。',
        en: 'A quantum gate is not a pulse label but the channel generated by a controlled Hamiltonian over a fixed interval; experiment must infer that channel and feed discrepancies back to the model.',
      }}
      conclusion={{
        zh: '单比特旋转由驱动幅度、相位和失谐构造；双比特条件相位由态依赖相互作用构造。两者都必须通过布居、相位、泄漏和损失共同验收。',
        en: 'Single-qubit rotations are constructed from drive amplitude, phase and detuning; two-qubit conditional phases are constructed from state-dependent interactions. Both require joint acceptance of population, phase, leakage and loss.',
      }}
      language={language}
    >
      <div className="gate-control-loop" aria-label={language === 'zh' ? '量子门理论与实验闭环' : 'Quantum-gate theory and experiment loop'}>
        <div className="gate-control-loop__principle">
          <span>{language === 'zh' ? '动力学约束' : 'Dynamical constraint'}</span>
          <MapEquation source={String.raw`U(T)=\mathcal T\exp\!\left[-\frac{i}{\hbar}\int_0^T H[u(t)]\,dt\right]`} />
        </div>

        <ol className="gate-control-loop__track">
          {gateLoopNodes.map((node, index) => (
            <li className={`gate-step gate-step--${node.id}`} key={node.id}>
              <span>{String(index + 1).padStart(2, '0')}</span>
              <h3><WikiText text={node.title[language]} language={language} /></h3>
              {node.formula ? <MapEquation source={node.formula} /> : null}
              <p>{node.detail[language]}</p>
            </li>
          ))}
        </ol>
        <div className="gate-control-loop__feedback" aria-hidden="true"><span>{language === 'zh' ? '模型修正' : 'model revision'}</span><i /></div>

        <div className="gate-hamiltonian-branches">
          <article>
            <header><span>1Q</span><h3>{language === 'zh' ? '旋转轴与角度' : 'Rotation axis and angle'}</h3></header>
            <MapEquation source={String.raw`\frac{H_{1q}}{\hbar}=\frac{1}{2}\!\left[\Omega\cos\phi\,X+\Omega\sin\phi\,Y+\Delta Z\right]`} />
            <p>{language === 'zh' ? '脉冲面积给出旋转角，光学或微波相位给出赤道面旋转轴，失谐产生 Z 分量。' : 'Pulse area sets the rotation angle, optical or microwave phase sets the equatorial axis, and detuning supplies the Z component.'}</p>
          </article>
          <article>
            <header><span>2Q</span><h3><WikiText text={language === 'zh' ? 'Rydberg 阻塞与条件相互作用' : 'Rydberg blockade and conditional interaction'} language={language} /></h3></header>
            <MapEquation source={String.raw`\frac{H_{2q}}{\hbar}=\sum_{j=1}^{2}\frac{\Omega_j}{2}(|r_j\rangle\langle1_j|+\mathrm{h.c.})+V_{rr}|rr\rangle\langle rr|`} />
            <p>{language === 'zh' ? 'Rydberg 相互作用改变双激发支路的能量；选定闭合轨迹，使计算基态获得目标条件相位并抑制残余布居。' : 'Rydberg interaction shifts the doubly excited branch; a closed trajectory returns population while imprinting the target conditional phase.'}</p>
          </article>
        </div>
      </div>
    </CoreQuestionFrame>
  )
}
